2020:03:30 00:12:50:189829 ~ Traceback (most recent call last):
  File "C:\SDK\Anaconda3\lib\site-packages\pydebugger\debug.py", line 222, in read_config
    data = self.cfg.get(section, option)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'DEBUG'

2020:03:30 00:13:07:342547 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:03:30 00:13:09:513737 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

